[package]
name = "rust-meth"
version = "0.1.1"
edition = "2024"
description = "Print all methods available on any Rust type, powered by rust-analyzer"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/saylesss88/rust-meth"
repository = "https://github.com/saylesss88/rust-meth"
documentation = "https://docs.rs/rust-meth"
readme = "README.md"
keywords = ["rust-analyzer", "lsp", "methods", "cli", "introspection"]
categories = ["command-line-utilities", "development-tools"]
exclude = [".github", "*.gif", "*.png"]

[[bin]]
name = "rust-meth"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
dialoguer = {version = "0.12", features = [
	"fuzzy-select",
], default-features = false}
fuzzy-matcher = "0.3.7"
serde_json = "1.0.149"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
