[package]
name = "rust-meth"
version = "0.2.2"
edition = "2024"
authors = ["T. Sawyer <saylesss87@proton.me>"]
description = "Discover methods available on any Rust type with fuzzy filtering, inline documentation, interactive selection, and go-to-definition."
license = "Apache-2.0"
homepage = "https://github.com/saylesss88/rust-meth"
repository = "https://github.com/saylesss88/rust-meth"
documentation = "https://docs.rs/rust-meth"
readme = "README.md"
keywords = ["rust-analyzer", "lsp", "methods", "cli", "introspection"]
categories = ["command-line-utilities", "development-tools"]
exclude = [".github", "*.gif", "*.png", "tests/", "benches/", "assets/"]

[[bin]]
name = "rust-meth"
path = "src/main.rs"

[dependencies]
rust-meth-lib = {workspace = true}
anyhow = {version = "1.0.102", default-features = false}

[lints.rust]
unsafe_code = "forbid"
future_incompatible = {level = "warn", priority = -1}
nonstandard_style = {level = "warn", priority = -1}
rust_2018_idioms = {level = "warn", priority = -1}

[lints.clippy]
all = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = -1}
